# Generated by Django 4.2.30 on 2026-06-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_department_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'User/Staff'), ('auditor', 'Auditor '), ('manager', 'Manager'), ('maintenance', 'Maintenance Technician')], default='staff', max_length=20),
        ),
    ]
