# Generated by Django 4.2.30 on 2026-05-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_maintenance_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('buying', 'Buying'), ('active', 'Active'), ('maintenance', 'In Maintenance'), ('inactive', 'Inactive'), ('disposed', 'Disposed')], db_index=True, default='active', max_length=20),
        ),
    ]
